ALTER TABLE projects ADD COLUMN IF NOT EXISTS wallet_address VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS website VARCHAR(512) NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS contact VARCHAR(256) NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_projects_wallet ON projects(wallet_address);
